---
title: "RDD Main Results with Additional Bandwidths and a Rectangular Kernel"
author: "DB"
date: "2023-12-08"
output: pdf_document
---

```{r}
library(modelsummary)
library(kableExtra)
library(gt)
library(estimatr)
library(rdrobust)
library(rddtools)
library(haven)
library(Hmisc)
library(tidyverse)
library(rddapp)
library(mosaic)

``` 


```{r}
rm(list = ls())
```



```{r}
#Loading the the main datasets for adults and children 
Unco_DS_final<- read.csv(".../Replication Package Palm Oil Concessions Belgian Congo/Datasets/Unco_DS_final.csv", header=TRUE)


#creating the subsets
Unco_DS_final_60km <- Unco_DS_final %>% 
  filter(dist_concess_bord < 60000)
Unco_DS_final_30km <- Unco_DS_final %>% 
  filter(dist_concess_bord < 30000)



DHS_Children_final <- read.csv('.../Replication Package Palm Oil Concessions Belgian Congo/Datasets/DHS_Children_final.csv', header=TRUE)

ß
```



```{r}
# Finding out the number of the respective clusters inside and outside the clusters. 
Unco_DS_final_20km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 20)
Unco_DS_final_25km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 25)
Unco_DS_final_35km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 35)
Unco_DS_final_40km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 40)
Unco_DS_final_45km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 45)
Unco_DS_final_50km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 50)
Unco_DS_final_55km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km < 55)


DHS_Children_final_20km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 20)
DHS_Children_final_25km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 25)
DHS_Children_final_35km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 35)
DHS_Children_final_40km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 40)
DHS_Children_final_45km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 45)
DHS_Children_final_50km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 50)
DHS_Children_final_55km <- DHS_Children_final %>% 
  filter(dist_concess_bord_km < 55)
```


```{r}
Unco_DS_final_55km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_55km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_50km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_50km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_45km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_45km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_40km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_40km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_35km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_35km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_25km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_25km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_20km %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_20km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


#               'Total Number Clusters',      '10', '22','45', '49', '53','61','63',
#               'Clusters within Con. Area',   '2', '7', '14', '16', '17','21','21')

```



```{r}

######################################################################################################################
#RD estimates for Wealth Index (additional Bandwiths) with a rectangular kernel.
######################################################################################################################

#Running a loop with the following bandwiths 
attach(Unco_DS_final)

bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel= "rectangular")
assign(model,m)
}
detach(Unco_DS_final)


# Taking the less = TRUE option as default version. The following code is adapted to that! 

tidy.rd <- function(x, ...) {
    s <- summary(x, ...)
    ret <- data.frame(
      term      = row.names(s$coefficients),
      estimate  = s$coefficients[, 3],
      std.error = s$coefficients[, 4],
      conf.low  = s$coefficients[, 5],
      conf.high = s$coefficients[, 6])
    ret
}

glance.rd <- function(x, ...) {
    ret <- data.frame(
      Bandwidth = x$bw[2],
      nobs = x$obs[2])
    ret
}


# Adjusting the robust standard errors since the default standard errors are different
tidy_custom.rd <- function(x, ...) {
    s <- summary(x)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8])
    return(out)
}


#Adding Mean Dep. Var.
glance_custom.rd <- function(x, ...) {
  dv <- x$model[[2]]$model$Y
  dv_mean <- sprintf("%.3f", mean(dv, na.rm = TRUE))
  dv_sd <- sprintf("%.3f", sd(dv, na.rm = TRUE))
  data.table::data.table(`Mean Dep. Var.` = dv_mean, `SD Dep. Var.` = dv_sd)
}


# Main variable structure. 
Var_Structure <- c("Opt" = "Inside Concession",
                   "Usr" = "Inside Concession")

#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS, ~OLS, ~OLS,~OLS,
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X','X',
                'Total Number Clusters',      '10', '22','45', '49', '53','61','63',
                'Clusters within Con. Area',   '2', '7', '14', '16', '17','21','21')
attr(Add_info_RDD, 'position') <- c(5,7,8,9)

#Structuring model statistics.
gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "Num.Obs.",             0,
  "Bandwidth", "Bandwidth", 2,
  "Mean Dep. Var.", "Mean Dep. Var.", 3,
  "SD Dep. Var.", "SD Dep. Var.", 3)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Wealth Aditional Bandwidths", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Wealth Index Estimates for Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Wealth Index " = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Wealth_Index_additional_bandwidths_rectangular_table.tex")


```



```{r}

######################################################################################################################
#RD estimates for Wealth Factor Score (Additional Bandwiths) with a rectangular kernel.
######################################################################################################################
attach(Unco_DS_final)


#Running a loop with the following bandwiths 
bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel = "rectangular")
assign(model,m)
}
detach(Unco_DS_final)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Wealth Factor Score (additional Bandwidths)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Wealth Factor Score Estimates for Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Wealth Factor Score " = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Wealth_Factor_Score_additional_bandwidths_rectangular_table.tex")


```



```{r}

######################################################################################################################
#RD estimates for Total Years of Education (Additional Bandwiths) with a rectangular kernel.
######################################################################################################################
attach(Unco_DS_final)

bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Total_Years_Education~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel= "triangular")
assign(model,m)
}
detach(Unco_DS_final)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Years of Education (additional Bandwidths)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Years of Education Estimates for Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Total Number of Years of Education" = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Total_Years_Education_additional_bandwidths_rectangular_table.tex")


```


```{r}

######################################################################################################################
#RD estimates for Literacy (Additional Bandwiths) with a rectangular kernel.
######################################################################################################################
attach(Unco_DS_final)

bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel= "triangular")
assign(model,m)
}
detach(Unco_DS_final)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Literacy (additional Bandwidths)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Literacy Estimates for Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Literacy" = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Literacy_additional_bandwidths_rectanglar_table.tex")


```



```{r}

######################################################################################################################
#RD estimates for Height/Age Percentile for Women (Additional Bandwidths) with a rectangular kernel.
######################################################################################################################
attach(Unco_DS_final)

bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km | age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel = "rectangular")
assign(model,m)
}
detach(Unco_DS_final)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Height/Age Percentile for Women (additional Bandwidths)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Height/Age Percentile Estimates for Women with Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Height/Age Percentile for Women" = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_HAP_Women_additional_bandwidths_rectanglar_table.tex")


```


```{r}

######################################################################################################################
#RD estimates for Wealth Factor Score (additional Bandwidths) with a rectangular kernel.
######################################################################################################################
attach(DHS_Children_final)

bw <- c(20,25,35,40,45,50,55)
for(i in 1:length(bw)){
model <- paste("Rd_est_add_bandwidth_",bw[i],"km", sep="")
m<- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km | Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = DHS_Children_final, bw = bw[i], cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE, kernel =)
assign(model,m)
}
detach(DHS_Children_final)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_add_bandwidth_20km, "RDD2" = Rd_est_add_bandwidth_25km, "RDD3"= Rd_est_add_bandwidth_35km, "RDD4" = Rd_est_add_bandwidth_40km, "RDD5" = Rd_est_add_bandwidth_45km, "RDD6" = Rd_est_add_bandwidth_50km, "RDD7" =Rd_est_add_bandwidth_55km)

modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Height/Age Percentile for Children (additional Bandwidths)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 3, title = "RDD Height/Age Percentile for Children Estimates with Additional Bandwidths using a Rectangular Kernel", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Height/Age Percentile for Children" = 7))  %>% kable_styling(latex_options = c( "scale_down","hold_position"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_HAP_Children_additional_bandwidths_rectangular_table.tex")


```






























