---
title: "RDD Main Results with Placebo Borders"
author: "DB"
date: "2023-12-08"
output: pdf_document
---

```{r}
rm(list = ls())
```

```{r}
library(modelsummary)
library(kableExtra)
library(gt)
library(estimatr)
library(rdrobust)
library(rddtools)
library(haven)
library(Hmisc)
library(tidyverse)
library(rddapp)
library(mosaic)

``` 


```{r}
rm(list = ls())
```

```{r}
Unco_DS_final<- read.csv(".../Unco_DS_final.csv", header=TRUE)





DHS_Children_final <- read.csv('.../DHS_Children_final.csv', header=TRUE)


```






```{r}
######################################################################################################################
#RD estimates for Wealth Index and Log Wealth Index Factor Score (optimal as well as fixed bandwidth of 60km and 30km)
# Having the border at 50 km. 
######################################################################################################################


attach(Unco_DS_final)
Rd_est_Wealth_index_optimal <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10 , cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Wealth_index_optimal)


Rd_est_Wealth_index_60km <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Wealth_index_60km)

Rd_est_Wealth_index_30km <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Wealth_index_30km)


Rd_est_Wealth_Factor_Score_optimal <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_optimal)

Rd_est_Wealth_Factor_Score_60km <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_60km)

Rd_est_Wealth_Factor_Score_30km <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, cutpoint = -10, data = Unco_DS_final, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_30km)

detach(Unco_DS_final)



#############################################################################
#Adjusting modelsummary_table for displaying regression table of rd_est model
#############################################################################

# Taking the less = TRUE option as default version. The following code is adapted to that! 

tidy.rd <- function(x, ...) {
    s <- summary(x, ...)
    ret <- data.frame(
      term      = row.names(s$coefficients),
      estimate  = s$coefficients[, 3],
      std.error = s$coefficients[, 4],
      conf.low  = s$coefficients[, 5],
      conf.high = s$coefficients[, 6])
    ret
}

glance.rd <- function(x, ...) {
    ret <- data.frame(
      Bandwidth = x$bw[2],
      nobs = x$obs[2])
    ret
}


# Adjusting the robust standard errors since the default standard errors are different
tidy_custom.rd <- function(x, ...) {
    s <- summary(x)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8])
    return(out)
}


#Adding Mean Dep. Var.
glance_custom.rd <- function(x, ...) {
  dv <- x$model[[2]]$model$Y
  dv_mean <- sprintf("%.3f", mean(dv, na.rm = TRUE))
  dv_sd <- sprintf("%.3f", sd(dv, na.rm = TRUE))
  data.table::data.table(`Mean Dep. Var.` = dv_mean, `SD Dep. Var.` = dv_sd)
}


# Main variable structure. 
Var_Structure <- c("Opt" = "Inside Concession",
                   "Usr" = "Inside Concession")

#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS, ~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '12', '63','24', '11', '63','24',
                'Clusters within Con. Area', '9', '22','15', '8', '23','15')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)

#Structuring model statistics.
gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "Num.Obs.",             0,
  "Bandwidth", "Bandwidth", 2,
  "Mean Dep. Var.", "Mean Dep. Var.", 3,
  "SD Dep. Var.", "SD Dep. Var.", 3)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Wealth_index_optimal, "RDD2" = Rd_est_Wealth_index_60km, "RDD3"= Rd_est_Wealth_index_30km, "RDD4" = Rd_est_Wealth_Factor_Score_optimal, "RDD5" = Rd_est_Wealth_Factor_Score_60km, "RDD6" = Rd_est_Wealth_Factor_Score_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Wealth (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Wealth (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Wealth Index " = 3, "Log(Wealth Factor Score)" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Wealth_final_Placebo_Border_50km_table.tex")

```

```{r}

#Adjusting the border to get the right Numbers of Cluster inside and outside the Concession Areas. 

# Setting the Border at 50km = 0
Unco_DS_final <- Unco_DS_final %>% 
  mutate(within.con_placebo50 = ifelse (dist.cenpo_km < 50, 1,0))

Unco_DS_final <- Unco_DS_final %>% 
  mutate(dist_concess_bord_km_placebo50 = ifelse(within.con_placebo50==1, (50-dist.cenpo_km), dist.cenpo_km-50))

# Limiting the Dataset to the chosen bandwidth
# Here for the optimal bandwidth
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Wealth_index_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Wealth_Factor_Score_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


# Getting the number of Clusters for 60 and 30 km. 
Unco_DS_final_Placeborder50km_60km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < 60)
Unco_DS_final_Placeborder50km_30km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < 30)

Unco_DS_final_Placeborder50km_60km %>%
  group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_Placeborder50km_60km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


Unco_DS_final_Placeborder50km_30km %>%
  group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_Placeborder50km_30km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```


```{r}
##############################################################################################################
#RD estimates for Total Years of Education and Literacy (optimal as well as fixed bandwidth of 60km  and 30km)
# Having the border at 50 km. 
##############################################################################################################


attach(Unco_DS_final)
Rd_est_Total_Years_Education_optimal <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Total_Years_Education_optimal)


Rd_est_Total_Years_Education_60km <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Total_Years_Education_60km)

Rd_est_Total_Years_Education_30km <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", kernel= "triangular")
summary(Rd_est_Total_Years_Education_30km)


Rd_est_Literacy_adjusted_optimal <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_optimal)


Rd_est_Literacy_adjusted_60km <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_60km)

Rd_est_Literacy_adjusted_30km <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_30km)

detach(Unco_DS_final)



#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS,~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '22', '63','24', '27', '63','24',
                'Clusters within Con. Area', '14', '22','15', '16', '22','15')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)








Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Total_Years_Education_optimal, "RDD2" = Rd_est_Total_Years_Education_60km,"RDD3"= Rd_est_Total_Years_Education_30km, "RDD4" = Rd_est_Literacy_adjusted_optimal, "RDD5" = Rd_est_Literacy_adjusted_60km, "RDD6" =Rd_est_Literacy_adjusted_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Education (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Education <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Education (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Years of Education " = 3, "Literacy" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Education, file = "Unco_Education_final_Placebo_Border_50km_table.tex")
```


```{r}

# Limiting the Dataset to the chosen bandwidth.
# Here for the optimal bandwidth.
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Total_Years_Education_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Literacy_adjusted_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con_placebo50) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```







```{r}
##################################################################################################################################
#RD estimates for Height/Age Percentile (Women) and Height/Age Percentile (Children)  (optimal as well as fixed bandwidth of 60km and 30km)
# Having the border at 50 km. 
##################################################################################################################################


attach(Unco_DS_final)
Rd_est_Height_Age_Women_optimal <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square  + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Height_Age_Women_optimal)


Rd_est_Height_Age_Women_60km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Height_Age_Women_60km)

Rd_est_Height_Age_Women_30km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = -10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", kernel = "triangular")
summary(Rd_est_Height_Age_Women_30km)
detach(Unco_DS_final)

attach (DHS_Children_final)
Rd_est_Height_Age_Children_optimal <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km | Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = DHS_Children_final, cutpoint = -10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Height_Age_Children_optimal)

Rd_est_Height_Age_Children_60km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = DHS_Children_final, cutpoint = -10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Height_Age_Children_60km)

Rd_est_Height_Age_Children_30km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = DHS_Children_final,  cutpoint = -10, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l", kernel ="triangular")
summary(Rd_est_Height_Age_Children_30km)
detach(DHS_Children_final)



#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS, ~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '28', '63','24', '72', '63','24',
                'Clusters within Con. Area', '17', '22','15', '23', '22','15')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)






Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Height_Age_Women_optimal, "RDD2" = Rd_est_Height_Age_Women_60km, "RDD3" = Rd_est_Height_Age_Women_30km, "RDD4" = Rd_est_Height_Age_Children_optimal, "RDD5" = Rd_est_Height_Age_Children_60km, "RDD6"= Rd_est_Height_Age_Children_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Health (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Health <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Health (Placebo Border at 50 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Height/ Age Percentile (Women)" = 3, "Height/ Age Percentile (Children)" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Health, file = "Unco_Health_final_Placebo_Border_50km_table.tex")
```


```{r}

# Limiting the dataset to the chosen bandwidth.
# Here for the optimal bandwidth.
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Height_Age_Women_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

#Brief note: There are obsevations for every Cluster within the Children Dataset, which is why also the Unco_DS_finl Dataset can be taken for calculating the number of clusters. 
Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo50 < Rd_est_Height_Age_Children_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```



```{r}
######################################################################################################################
#RD estimates for Wealth Index and Log Wealth Index Factor Score (optimal aswell as fixed bandwidth of 60km and 30km)
# Having the border at 70 km. 
######################################################################################################################


attach(Unco_DS_final)
Rd_est_Wealth_index_optimal <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10 , cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Wealth_index_optimal)


Rd_est_Wealth_index_60km <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Wealth_index_60km)

Rd_est_Wealth_index_30km <- rd_est(formula = Wealth_Index ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Wealth_index_30km)


Rd_est_Wealth_Factor_Score_optimal <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_optimal)

Rd_est_Wealth_Factor_Score_60km <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_60km)

Rd_est_Wealth_Factor_Score_30km <- rd_est(formula = Log_Wealth_Index_Factor_Score ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, cutpoint = +10, data = Unco_DS_final, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Wealth_Factor_Score_30km)

detach(Unco_DS_final)



#############################################################################
#Adjusting modelsummary_table for displaying regression table of rd_est model
#############################################################################

# Taking the less = TRUE option as default version. The following code is adapted to that! 

tidy.rd <- function(x, ...) {
    s <- summary(x, ...)
    ret <- data.frame(
      term      = row.names(s$coefficients),
      estimate  = s$coefficients[, 3],
      std.error = s$coefficients[, 4],
      conf.low  = s$coefficients[, 5],
      conf.high = s$coefficients[, 6])
    ret
}

glance.rd <- function(x, ...) {
    ret <- data.frame(
      Bandwidth = x$bw[2],
      nobs = x$obs[2])
    ret
}


# Adjusting the robust standard errors since the default standard errors are different
tidy_custom.rd <- function(x, ...) {
    s <- summary(x)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8])
    return(out)
}


#Adding Mean Dep. Var.
glance_custom.rd <- function(x, ...) {
  dv <- x$model[[2]]$model$Y
  dv_mean <- sprintf("%.3f", mean(dv, na.rm = TRUE))
  dv_sd <- sprintf("%.3f", sd(dv, na.rm = TRUE))
  data.table::data.table(`Mean Dep. Var.` = dv_mean, `SD Dep. Var.` = dv_sd)
}


# Main variable structure. 
Var_Structure <- c("Opt" = "Inside Concession",
                   "Usr" = "Inside Concession")

#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS, ~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '43', '73','35', '43', '73','35',
                'Clusters within Con. Area', '11', '25','6', '11', '25','6')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)

#Structuring model statistics.
gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "Num.Obs.",             0,
  "Bandwidth", "Bandwidth", 2,
  "Mean Dep. Var.", "Mean Dep. Var.", 3,
  "SD Dep. Var.", "SD Dep. Var.", 3)



Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Wealth_index_optimal, "RDD2" = Rd_est_Wealth_index_60km, "RDD3"= Rd_est_Wealth_index_30km, "RDD4" = Rd_est_Wealth_Factor_Score_optimal, "RDD5" = Rd_est_Wealth_Factor_Score_60km, "RDD6" = Rd_est_Wealth_Factor_Score_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Wealth (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Wealth <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Wealth (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Wealth Index " = 3, "Log(Wealth Factor Score)" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Wealth, file = "Unco_Wealth_final_Placebo_Border_70km_table.tex")

```

```{r}
###########################################################################
# Now Running main Regressions with Placebo Border at 70 km
###########################################################################

#Adjusting the border to get the right Numbers of Cluster inside and outside the Concession Areas. 


Unco_DS_final <- Unco_DS_final %>% 
  mutate(within.con_placebo70 = ifelse (dist.cenpo_km < 70, 1,0))

# Setting the Border at 70km = 0
Unco_DS_final <- Unco_DS_final %>% 
  mutate(dist_concess_bord_km_placebo70 = ifelse(within.con_placebo70==1, (70-dist.cenpo_km), dist.cenpo_km-70))

# Limiting the Dataset to the chosen bandwidth
# Here for the optimal bandwidth
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Wealth_index_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Wealth_Factor_Score_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


# Getting the number of Clusters for 60 and 30 km. 
Unco_DS_final_Placeborder70km_60km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < 60)
Unco_DS_final_Placeborder70km_30km <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < 30)

Unco_DS_final_Placeborder70km_60km %>%
  group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_Placeborder70km_60km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


Unco_DS_final_Placeborder70km_30km %>%
  group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_Placeborder70km_30km %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```






```{r}
##############################################################################################################
#RD estimates for Total Years of Education and Literacy (optimal as well as fixed bandwidth of 60km  and 30km)
# Having the border at 70 km. 
##############################################################################################################


attach(Unco_DS_final)
Rd_est_Total_Years_Education_optimal <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km |  gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Total_Years_Education_optimal)


Rd_est_Total_Years_Education_60km <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Total_Years_Education_60km)

Rd_est_Total_Years_Education_30km <- rd_est(formula = Total_Years_Education ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", kernel= "triangular")
summary(Rd_est_Total_Years_Education_30km)


Rd_est_Literacy_adjusted_optimal <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_optimal)


Rd_est_Literacy_adjusted_60km <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_60km)

Rd_est_Literacy_adjusted_30km <- rd_est(formula = Literacy_adjusted ~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Literacy_adjusted_30km)

detach(Unco_DS_final)




#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS, ~OLS, ~OLS, ~OLS,~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '50', '73','35', '69', '73','35',
                'Clusters within Con. Area', '14', '25','6', '23', '25','6
                
                ')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)









Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Total_Years_Education_optimal, "RDD2" = Rd_est_Total_Years_Education_60km,"RDD3"= Rd_est_Total_Years_Education_30km, "RDD4" = Rd_est_Literacy_adjusted_optimal, "RDD5" = Rd_est_Literacy_adjusted_60km, "RDD6" =Rd_est_Literacy_adjusted_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Education (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Education <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Education (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Years of Education " = 3, "Literacy" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Education, file = "Unco_Education_final_Placebo_Border_70km_table.tex")
```


```{r}

# Limiting the Dataset to the chosen bandwidth
# Here for the optimal bandwidth
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Total_Years_Education_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Literacy_adjusted_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```





```{r}
##################################################################################################################################
#RD estimates for Height/Age Percentile (Women) and Height/Age Percentile (Children)  (optimal as well as fixed bandwidth of 60km and 30km)
# Having the border at 70 km. 
##################################################################################################################################


attach(Unco_DS_final)
Rd_est_Height_Age_Women_optimal <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square  + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", verbose = FALSE)
summary(Rd_est_Height_Age_Women_optimal)


Rd_est_Height_Age_Women_60km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l")
summary(Rd_est_Height_Age_Women_60km)

Rd_est_Height_Age_Women_30km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  age + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = Unco_DS_final, cutpoint = +10, bw = 30, cluster = DHS_Cluster_adj, less= TRUE, t.design = "l", kernel = "triangular")
summary(Rd_est_Height_Age_Women_30km)
detach(Unco_DS_final)

attach (DHS_Children_final)
Rd_est_Height_Age_Children_optimal <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km | Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga, data = DHS_Children_final, cutpoint = +10, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Height_Age_Children_optimal)

Rd_est_Height_Age_Children_60km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = DHS_Children_final, cutpoint = +10, bw = 60, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l")
summary(Rd_est_Height_Age_Children_60km)

Rd_est_Height_Age_Children_30km <- rd_est(formula = Height.Age_Percentile_adj ~ dist_concess_bord_cen_km |  Child_gender + Child_Age_months + age_square + Dummy_Survey_Year + Brabanta + Elisabetha + Flandria + Lusanga, data = DHS_Children_final,  cutpoint = +10, bw = 30, cluster = DHS_Cluster_adj, less = TRUE, t.design = "l", kernel ="triangular")
summary(Rd_est_Height_Age_Children_30km)
detach(DHS_Children_final)




#Adding further information to the table.
Add_info_RDD <- tribble( ~term, ~OLS,  ~OLS, ~OLS, ~OLS, ~OLS, ~OLS,
                'Bandwidth Choice', 'Optimal','Wide','Narrow','Optimal','Wide','Narrow',    
                'Std.Errors','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster','DHS Cluster',
                'Fixed Effects', 'X', 'X', 'X', 'X','X', 'X',
                'Total Number Clusters', '49', '73','35', '90', '73','35',
                'Clusters within Con. Area', '14', '25','6', '27', '25','6')
attr(Add_info_RDD, 'position') <- c(5,7,8,9,10)






Model_Summary_Rd_est_results <- list("RDD1" = Rd_est_Height_Age_Women_optimal, "RDD2" = Rd_est_Height_Age_Women_60km, "RDD3" = Rd_est_Height_Age_Women_30km, "RDD4" = Rd_est_Height_Age_Children_optimal, "RDD5" = Rd_est_Height_Age_Children_60km, "RDD6"= Rd_est_Height_Age_Children_30km)

modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Health (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "gt")


RDD_Unco_final_table_Health <- modelsummary(Model_Summary_Rd_est_results, fmt = 4, title = "RDD Health (Placebo Border at 70 km)", estimate = "estimate", stars = TRUE, coef_map = Var_Structure, gof_map = gm, add_rows = Add_info_RDD, notes = list("Test for note1"),  output = "latex") %>%
 add_header_above(c(" " = 1, "Height/ Age Percentile (Women)" = 3, "Height/ Age Percentile (Children)" = 3))  %>% kable_styling(latex_options = c( "scale_down"))

kableExtra::save_kable(RDD_Unco_final_table_Health, file = "Unco_Health_final_Placebo_Border_70km_table.tex")
```



```{r}

# Limiting the Dataset to the chosen bandwidth
# Here for the optimal bandwidth
Unco_DS_final_optimal_1 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Height_Age_Women_optimal$bw[2])
Unco_DS_final_optimal_1 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_1 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

#Brief note: There are obsevations for every Cluster within the Children Dataset, which is why also the Unco_DS_finl Dataset can be taken for Calculating the number of Clusters. 
Unco_DS_final_optimal_2 <- Unco_DS_final %>% 
  filter(dist_concess_bord_km_placebo70 < Rd_est_Height_Age_Children_optimal$bw[2])
Unco_DS_final_optimal_2 %>%   group_by(within.con_placebo70) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
Unco_DS_final_optimal_2 %>% 
summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

```

