---
title: "RDD Results per Age Cohort"
author: "DB"
date: "2023-12-08"
output: pdf_document
---

```{r}
library(modelsummary)
library(kableExtra)
library(gt)
library(estimatr)
library(rdrobust)
library(rddtools)
library(haven)
library(Hmisc)
library(tidyverse)
library(rddapp)
library(mosaic)

``` 

```{r}
rm(list = ls())
```

```{r}
Unco_DS_final<- read.csv(".../Replication Package Palm Oil Concessions Belgian Congo/Datasets/Unco_DS_final.csv", header=TRUE)


#Creating the subsets.
Unco_DS_final_60km <- Unco_DS_final %>% 
  filter(dist_concess_bord < 60000)
Unco_DS_final_30km <- Unco_DS_final %>% 
  filter(dist_concess_bord < 30000)



DHS_Children_final <- read.csv('.../Replication Package Palm Oil Concessions Belgian Congo/Datasets/DHS_Children_final.csv', header=TRUE)


```


```{r}
##############################################################################################################################
#  Constructing function that calculates RD estimates for every age cohort and bandwidth.
##############################################################################################################################




Age_Cohort_Function <- function(byear, bw, v) { 
  
# Creating subsample for every 5-year cohort. 
Unco_DS_final <- Unco_DS_final %>%
  mutate(Birth_Year = Survey_Year - age)
ly <- byear - 1
uy <- byear + 5
df <- Unco_DS_final %>% subset(Birth_Year > ly & Birth_Year <uy)


# Calculating the clusters inside and outside. 
numclu <- df %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


# Running the RD regression for two types of bandwidth (IK12 and manual bandwidth), as they are assigned to different classes. 
 if (bw == "IK12") {

# Running RD regression with optimal bandwidth IK12   
   attach(df)
reg <- rd_est(formula = as.formula(paste0(v,"~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga")), data = df, cluster = DHS_Cluster_adj, bw = bw, less= TRUE, t.design = "l", verbose = FALSE)
detach(df)

# Calculating the number of Clusters. 
bwreg <- reg$bw[2]
bwreg <- as.numeric(bwreg)

df_limited <- df %>% 
  filter(dist_concess_bord_km < bwreg)

numclu <- df_limited %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df_limited %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

# Saving the estimates. 
 s <- summary(reg)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8],
      nobs = reg$obs[2],
      N.Cluster = numclu$Number_Clusters,
      N.Cluster_inside = numcluin$Number_Clusters[2],
      Bandwidth_numeric = bwreg)

coef_est <- out %>%  subset(term == 'Opt' | term == "Usr")  %>% mutate(Birth_Year_Cohort = byear, Dv = v, Bandwidth = bw) 
coef_est$Bandwidth <- str_replace(coef_est$Bandwidth, "IK12", "Optimal")  
  } else 
    {
# Same procedure for manually chosen bandwidths.       
bw <- as.numeric(bw)      
      attach(df)
reg <- rd_est(formula = as.formula(paste0(v,"~ dist_concess_bord_cen_km | gender + age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga")), data = df, cluster = DHS_Cluster_adj, bw = bw, less= TRUE, t.design = "l", verbose = FALSE)
detach(df)

bwreg <- reg$bw[2]
bwreg <- as.numeric(bwreg)


df_limited <- df %>% 
  filter(dist_concess_bord_km < bwreg)

numclu <- df_limited %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df_limited %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


 s <- summary(reg)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8],
      nobs = reg$obs[2],
      N.Cluster = numclu$Number_Clusters,
      N.Cluster_inside = numcluin$Number_Clusters[2],
      Bandwidth_numeric = bwreg)
    
coef_est <- out %>%  subset(term == 'Opt' | term == "Usr")  %>% mutate(Birth_Year_Cohort = byear, Dv = v, Bandwidth = bw) 

  }
      return(coef_est)
}
           

```




```{r}
###############################################################################################
# RD 5-year Cohort Coefficients for Wealth Index.
###############################################################################################

byear <- c(1945,1950,1955,1960,1965,1970,1975,1980,1985,1990,1995)
bw <- c(45,45,"IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12",60,60,60,60,60,60,60,60,60,60,60,30,30,30,30,30,30,30,30,30,30,30)
v <- c("Wealth_Index")
Age_Cohort_DS <- mapply(Age_Cohort_Function, byear, bw, v,  SIMPLIFY = FALSE) 
Age_Cohort_DS <- do.call("rbind",Age_Cohort_DS)
Age_Cohort_DS <- na.omit(Age_Cohort_DS)
  Age_Cohort_DS

  
groupcolor<-c("30"="orange", "60"="green4", "45"="grey" ,"Optimal"="navyblue")

#Leaving the Birth Corhots below 1955 because they do not render reasonable results. 
#For the 1950 cohort, the results are also significant. For the 1945 cohort, there are maximum 9 observations
Age_Cohort_DS <- Age_Cohort_DS %>% subset(Birth_Year_Cohort > 1955)

Age_Cohort_Wealth_Index <- Age_Cohort_DS %>% 
      ggplot(aes(x=Birth_Year_Cohort, y=estimate, color = Bandwidth)) +   geom_point(size=2,
             position = position_dodge(width = 2)) +
      geom_pointrange(aes(ymin=estimate-2*std.error, ymax=estimate+2*std.error), position = position_dodge(width = 2)) + 
      geom_hline(aes(yintercept=0), color="red") +  scale_colour_manual(values=groupcolor)+ labs(title="Wealth Index RD estimates per 5-year Cohort", x ="5-year Cohorts", y = "Wealth Index") + theme(plot.title = element_text(size = 16,,face = "bold"), axis.text = element_text(size = 16), axis.title = element_text(size = 17), legend.text = element_text(size = 16), legend.title = element_text(size = 16))
ggsave("Age_Cohort_Wealth_Index.png",  width=20, height=12, units = "cm")
Age_Cohort_Wealth_Index
```




```{r}
###############################################################################################
# RD 5-year Cohort Coefficients for Wealth Wealth Factor Score.
###############################################################################################

byear <- c(1945,1950,1955,1960,1965,1970,1975,1980,1985,1990,1995)
bw <- c(45,45,"IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12",60,60,60,60,60,60,60,60,60,60,60,30,30,30,30,30,30,30,30,30,30,30)
v <- c("Log_Wealth_Index_Factor_Score")
Age_Cohort_DS <- mapply(Age_Cohort_Function, byear, bw, v,  SIMPLIFY = FALSE) 
Age_Cohort_DS <- do.call("rbind",Age_Cohort_DS)
Age_Cohort_DS <- na.omit(Age_Cohort_DS)
  Age_Cohort_DS

  
groupcolor<-c("30"="orange", "60"="green4", "45"="grey" ,"Optimal"="navyblue")

#Leaving the Birth Corhots below 1955 because they do not render reasonable results. 
#For the 1950 cohort, the results are also significant. For the 1945 cohort, there are maximum 18 observations
Age_Cohort_DS <- Age_Cohort_DS %>% subset(Birth_Year_Cohort > 1955)

Age_Cohort_Wealth_Factor_Score <- Age_Cohort_DS %>% 
      ggplot(aes(x=Birth_Year_Cohort, y=estimate, color = Bandwidth)) +   geom_point(size=2,
             position = position_dodge(width = 2)) +
      geom_pointrange(aes(ymin=estimate-2*std.error, ymax=estimate+2*std.error), position = position_dodge(width = 2)) + 
      geom_hline(aes(yintercept=0), color="red") +  scale_colour_manual(values=groupcolor)+ labs(title="Wealth Index RD estimates per 5-year Cohort", x ="5-year Cohorts", y = "Wealth Factor Score") + theme(plot.title = element_text(size = 16,,face = "bold"), axis.text = element_text(size = 16), axis.title = element_text(size = 17), legend.text = element_text(size = 16), legend.title = element_text(size = 16))
ggsave("Age_Cohort_Wealth_Factor_Score.png",  width=20, height=12, units = "cm")
Age_Cohort_Wealth_Factor_Score
```


```{r}
###############################################################################################
# RD 5-year Cohort Coefficients for Total Years of Education.
###############################################################################################

byear <- c(1945,1950,1955,1960,1965,1970,1975,1980,1985,1990,1995)
bw <- c(45,45,"IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12",60,60,60,60,60,60,60,60,60,60,60,30,30,30,30,30,30,30,30,30,30,30)
v <- c("Total_Years_Education")
Age_Cohort_DS <- mapply(Age_Cohort_Function, byear, bw, v,  SIMPLIFY = FALSE) 
Age_Cohort_DS <- do.call("rbind",Age_Cohort_DS)
Age_Cohort_DS <- na.omit(Age_Cohort_DS)
  Age_Cohort_DS

  
groupcolor<-c("30"="orange", "60"="green4", "45"="grey" ,"Optimal"="navyblue")

#Leaving the Birth Corhots below 1955 because they do not render reasonable results since the respective regressions contain to few observations. 
Age_Cohort_DS <- Age_Cohort_DS %>% subset(Birth_Year_Cohort > 1955)

Age_Cohort_Total_Years_Education <- Age_Cohort_DS %>% 
      ggplot(aes(x=Birth_Year_Cohort, y=estimate, color = Bandwidth)) +   geom_point(size=2,
             position = position_dodge(width = 2)) +
      geom_pointrange(aes(ymin=estimate-2*std.error, ymax=estimate+2*std.error), position = position_dodge(width = 2)) + 
      geom_hline(aes(yintercept=0), color="red") +  scale_colour_manual(values=groupcolor)+ labs(title="Total Years of Education RD estimates per 5-year Cohort", x ="5-year Cohorts", y = "Total Years of Education") + theme(plot.title = element_text(size = 16,,face = "bold"), axis.text = element_text(size = 16), axis.title = element_text(size = 17), legend.text = element_text(size = 16), legend.title = element_text(size = 16))
ggsave("Age_Cohort_Total_Years_Education.png",  width=20, height=12, units = "cm")
Age_Cohort_Total_Years_Education
```


```{r}
###############################################################################################
# RD 5-year Cohort Coefficients for Literacy.
###############################################################################################

byear <- c(1945,1950,1955,1960,1965,1970,1975,1980,1985,1990,1995)
bw <- c(45,45,"IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12",60,60,60,60,60,60,60,60,60,60,60,30,30,30,30,30,30,30,30,30,30,30)
v <- c("Literacy_adjusted")
Age_Cohort_DS <- mapply(Age_Cohort_Function, byear, bw, v,  SIMPLIFY = FALSE) 
Age_Cohort_DS <- do.call("rbind",Age_Cohort_DS)
Age_Cohort_DS <- na.omit(Age_Cohort_DS)
  Age_Cohort_DS

  
groupcolor<-c("30"="orange", "60"="green4", "45"="grey" ,"Optimal"="navyblue")

#Leaving the Birth Corhots below 1955 because they do not render reasonable results since the respective regressions contain to few observations. 
Age_Cohort_DS <- Age_Cohort_DS %>% subset(Birth_Year_Cohort > 1955)

Age_Cohort_Literacy <- Age_Cohort_DS %>% 
      ggplot(aes(x=Birth_Year_Cohort, y=estimate, color = Bandwidth)) +   geom_point(size=2,
             position = position_dodge(width = 2)) +
      geom_pointrange(aes(ymin=estimate-2*std.error, ymax=estimate+2*std.error), position = position_dodge(width = 2)) + 
      geom_hline(aes(yintercept=0), color="red") +  scale_colour_manual(values=groupcolor)+ labs(title="Literacy RD estimates per 5-year Cohort", x ="5-year Cohorts", y = "Literacy")  + theme(plot.title = element_text(size = 16,,face = "bold"), axis.text = element_text(size = 16), axis.title = element_text(size = 17), legend.text = element_text(size = 16), legend.title = element_text(size = 16))
ggsave("Age_Cohort_Literacy.png",  width=20, height=12, units = "cm")
Age_Cohort_Literacy
```


```{r}
###############################################################################################
# Adjusted Function for RD 5-year Cohort Coefficients for Height/Age Percentile for Women.
###############################################################################################



Age_Cohort_Function_Women <- function(byear, bw, v) { 
Unco_DS_final <- Unco_DS_final %>%
  mutate(Birth_Year = Survey_Year - age)
ly <- byear - 1
uy <- byear + 5
df <- Unco_DS_final %>% subset(Birth_Year > ly & Birth_Year <uy)
 
numclu <- df %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))

 if (bw == "IK12") {

   attach(df)
reg <- rd_est(formula = as.formula(paste0(v,"~ dist_concess_bord_cen_km | age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga")), data = df, cluster = DHS_Cluster_adj, bw = bw, less= TRUE, t.design = "l", verbose = FALSE)
detach(df)

bwreg <- reg$bw[2]
bwreg <- as.numeric(bwreg)

df_limited <- df %>% 
  filter(dist_concess_bord_km < bwreg)

numclu <- df_limited %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df_limited %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


 s <- summary(reg)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8],
      nobs = reg$obs[2],
      N.Cluster = numclu$Number_Clusters,
      N.Cluster_inside = numcluin$Number_Clusters[2],
      Bandwidth_numeric = bwreg)

coef_est <- out %>%  subset(term == 'Opt' | term == "Usr")  %>% mutate(Birth_Year_Cohort = byear, Dv = v, Bandwidth = bw) 
coef_est$Bandwidth <- str_replace(coef_est$Bandwidth, "IK12", "Optimal")  
  } else 
    {
bw <- as.numeric(bw)      
      attach(df)
reg <- rd_est(formula = as.formula(paste0(v,"~ dist_concess_bord_cen_km | age + age_square + Dummy_Survey_Year + Brabanta +  Elisabetha + Flandria + Lusanga")), data = df, cluster = DHS_Cluster_adj, bw = bw, less= TRUE, t.design = "l", verbose = FALSE)
detach(df)

bwreg <- reg$bw[2]
bwreg <- as.numeric(bwreg)


df_limited <- df %>% 
  filter(dist_concess_bord_km < bwreg)

numclu <- df_limited %>%  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))
numcluin <- df_limited %>%
  group_by(within.con) %>%
  summarize(Number_Clusters = n_distinct(DHS_Cluster_adj))


 s <- summary(reg)$coefficients
    out <- data.frame(
      term = row.names(s),
      
      estimate = s[,3],
      std.error = s[,4],
      p.value = s[,8],
      nobs = reg$obs[2],
      N.Cluster = numclu$Number_Clusters,
      N.Cluster_inside = numcluin$Number_Clusters[2],
      Bandwidth_numeric = bwreg)
    
coef_est <- out %>%  subset(term == 'Opt' | term == "Usr")  %>% mutate(Birth_Year_Cohort = byear, Dv = v, Bandwidth = bw) 

  }
      return(coef_est)
}
           


  
###############################################################################################
# RD 5-year Cohort Coefficients for Height/Age Percentile (Women).
###############################################################################################

byear <- c(1955,1960,1965,1970,1975,1980,1985,1990,1995)
bw <- c("IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12","IK12",60,60,60,60,60,60,60,60,60,30,30,30,30,30,30,30,30,30)
v <- c("Height.Age_Percentile_adj")
Age_Cohort_DS <- mapply(Age_Cohort_Function_Women, byear, bw, v,  SIMPLIFY = FALSE) 
Age_Cohort_DS <- do.call("rbind",Age_Cohort_DS)
Age_Cohort_DS <- na.omit(Age_Cohort_DS)
  Age_Cohort_DS

  
groupcolor<-c("30"="orange", "60"="green4", "45"="grey" ,"Optimal"="navyblue")


Age_Cohort_HAP_Women <- Age_Cohort_DS %>% 
      ggplot(aes(x=Birth_Year_Cohort, y=estimate, color = Bandwidth)) +   geom_point(size=2,
             position = position_dodge(width = 2)) +
      geom_pointrange(aes(ymin=estimate-2*std.error, ymax=estimate+2*std.error), position = position_dodge(width = 2)) + 
      geom_hline(aes(yintercept=0), color="red") +  scale_colour_manual(values=groupcolor)+ labs(title="Height/Age Percentile (Women) RD estimates per 5-year Cohort", x ="5-year Cohorts", y = "Height/Age Percentile for Women")  + theme(plot.title = element_text(size = 16,,face = "bold"), axis.text = element_text(size = 16), axis.title = element_text(size = 17), legend.text = element_text(size = 16), legend.title = element_text(size = 16))

ggsave("Age_Cohort_HAP_Women.png",  width=20, height=12, units = "cm")
Age_Cohort_HAP_Women
```







